import type { Metadata } from "next";
import { ReactNode } from "react";
import '@/src/app/styles/_vars.scss';
import '@/src/app/styles/mixins.scss';
import '@/src/app/styles/reset.scss';
import '@/src/app/styles/fonts.scss';

export const metadata: Metadata = {
  title: "Stories",
  description: "Generated by create next app",
};

type RootLayoutType = Readonly<{children: ReactNode}>

export default function RootLayout({children, }: RootLayoutType) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
