import type { Metadata } from "next";
import { ReactNode } from "react";
import "@/src/shared/lib/styles/_vars.scss";
import "@/src/shared/lib/styles/mixins.scss";
import "@/src/app/styles/reset.scss";
import "@/src/app/styles/fonts.scss";
import { Header } from "@/src/widgets/Header";

export const metadata: Metadata = {
   title: "Stories",
   description: "Generated by create next app",
};

type RootLayoutType = Readonly<{ children: ReactNode }>;

export default function RootLayout({ children }: RootLayoutType) {
   return (
      <html lang="en">
         <body>
            <div className="app">
               <Header />
               <main>{children}</main>
            </div>
         </body>
      </html>
   );
}
